[server]
port = 5003
address = "172.16.100.136"
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262730"
font = "sans serif"